<?php

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

namespace svc\models;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="tasks")
 */
class TaskLi
{
    /**
     * @ORM\Column(name="t_id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue
     * @var int
     */
    private $t_id;
    /**
     * @ORM\Column(name="p_id", type="integer", nullable=true)
     * @var int
     */
    private $p_id;
    /**
     * @ORM\Column(name="t_priority", type="integer")
     * @var int
     */
    private $t_priority;
    /**
     * @ORM\Column(name="t_date", type="string", length=65535)
     * @var string
     */
    private $t_date;
    /**
     * @ORM\Column(name="t_subject", type="string", length=65535)
     * @var string
     */
    private $t_subject;

    public function get_t_id()
    {
        return $this->t_id;
    }

    public function set_t_id($value)
    {
        $this->t_id = $value;
    }

    public function get_p_id()
    {
        return $this->p_id;
    }

    public function set_p_id($value)
    {
        $this->p_id = $value;
    }

    public function get_t_priority()
    {
        return $this->t_priority;
    }

    public function set_t_priority($value)
    {
        $this->t_priority = $value;
    }

    public function get_t_date()
    {
        return $this->t_date;
    }

    public function set_t_date($value)
    {
        $this->t_date = $value;
    }

    public function get_t_subject()
    {
        return $this->t_subject;
    }

    public function set_t_subject($value)
    {
        $this->t_subject = $value;
    }
}
