<?php

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

namespace dao;

include_once __DIR__ . '/../models/Task.php';

use models\Task;

class TasksDaoGenerated
{
    /**
     * @var \DataStore
     */
    protected $ds;

    public function __construct($ds)
    {
        $this->ds = $ds;
    }

    /**
     * (C)RUD: tasks
     * Generated/AI values are passed to $p param
     * @param Task $p
     * @return void
     * @throws \Exception
     */
    public function create_task($p)
    {
        $this->ds->create($p);
    }

    /**
     * C(R)UD: tasks
     * @return Task[]
     * @throws \Exception
     */
    public function read_task_list()
    {
        return $this->ds->readAll(Task::class);
    }

    /**
     * C(R)UD: tasks
     * @param int $t_id
     * @return Task|FALSE on failure
     * @throws \Exception
     */
    public function read_task($t_id)
    {
        return $this->ds->read(Task::class, array("t_id" => $t_id));
    }

    /**
     * CR(U)D: tasks
     * @param Task $p
     * @throws \Exception
     */
    public function update_task($p)
    {
        return $this->ds->update($p);
    }

    /**
     * CRU(D): tasks
     * @param int $t_id
     * @throws \Exception
     */
    public function delete_task($t_id)
    {
        return $this->ds->delete(Task::class, array("t_id" => $t_id));
    }
}
