<?php

namespace dal;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="tasks")
 */
class Task
{
    /**
     * @ORM\Column(name="t_id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue
     * @var int
     */
    private $tId;
    /**
     * @ORM\Column(name="g_id", type="integer")
     * @var int
     */
    private $gId;
    /**
     * @ORM\Column(name="t_priority", type="integer")
     * @var int
     */
    private $tPriority;
    /**
     * @ORM\Column(name="t_date", type="string", length=65535)
     * @var string
     */
    private $tDate;
    /**
     * @ORM\Column(name="t_subject", type="string", length=65535)
     * @var string
     */
    private $tSubject;
    /**
     * @ORM\Column(name="t_comments", type="string", length=65535, nullable=true)
     * @var string
     */
    private $tComments;

    public function getTId()
    {
        return $this->tId;
    }

    public function setTId($value)
    {
        $this->tId = $value;
    }

    public function getGId()
    {
        return $this->gId;
    }

    public function setGId($value)
    {
        $this->gId = $value;
    }

    public function getTPriority()
    {
        return $this->tPriority;
    }

    public function setTPriority($value)
    {
        $this->tPriority = $value;
    }

    public function getTDate()
    {
        return $this->tDate;
    }

    public function setTDate($value)
    {
        $this->tDate = $value;
    }

    public function getTSubject()
    {
        return $this->tSubject;
    }

    public function setTSubject($value)
    {
        $this->tSubject = $value;
    }

    public function getTComments()
    {
        return $this->tComments;
    }

    public function setTComments($value)
    {
        $this->tComments = $value;
    }
}